# Generated by Django 3.0.4 on 2020-03-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['bio']},
        ),
    ]
